from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field


class GenerationRequest(BaseModel):
    """
    Standardized request payload for LLM text generation.
    """
    prompt: str = Field(..., description="Main user/task prompt incorporating source data.")
    system_instruction: Optional[str] = Field(
        None,
        description="System instruction containing behavioral constraints and anti-fabrication rules.",
    )
    temperature: float = Field(0.2, ge=0.0, le=2.0, description="Sampling temperature.")
    max_tokens: Optional[int] = Field(None, description="Maximum tokens to generate.")
    response_format_json: bool = Field(True, description="Enforces structured JSON output where supported.")
    json_schema: Optional[Dict[str, Any]] = Field(None, description="Optional target JSON schema.")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class GenerationResponse(BaseModel):
    """
    Standardized response payload from LLM generation.
    """
    content: str = Field(..., description="Raw text or serialized JSON generated by the model.")
    model_name: str = Field(..., description="Name of the model utilized.")
    provider_name: str = Field(..., description="Name of the provider service.")
    finish_reason: Optional[str] = Field(None, description="Stop reason (e.g., stop, length, error).")
    usage: Optional[Dict[str, int]] = Field(
        None,
        description="Actual token usage metrics if provided by the model; null if unavailable.",
    )
    latency_ms: float = Field(0.0, description="Generation latency in milliseconds.")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class BaseLLMProvider(ABC):
    """
    Abstract Base Class for Generative Language Model Providers.
    Ensures provider-independent text generation across Gemini, OpenAI-compatible APIs, local models, and test mocks.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Identifier of the LLM provider."""
        pass

    @abstractmethod
    async def generate(self, request: GenerationRequest) -> GenerationResponse:
        """
        Executes generation asynchronously with automatic retry, timeout, and rate-limit handling.
        """
        pass
